### ISSUE TITLE
npm start commang gives error.

### ISSUE THREAD

**Issue by santhosh0209** [HafidzN/Inschatgram-Server#1]
MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.

Please help me.

**Comment by HafidzN** [comment]
Hi, that is simply because i hide some information such as mongoDB uri or jwt secret in dotenv file. Absolutely you can setup your own mongodb atlas and then replace my process.env.MONGODB_URL in the backend server's App.js with your newly generated mongodb uri. I hope it solve your problem.

**Comment by HoracioLopezCarvajal** [comment]
Hello, I am learning with the project, I have been thinking about the project, could you send me the censored configuration file with XXXX horaciolopezcarvajalspain@gmail.com
