### ISSUE TITLE
when i try to loginin and signup i got this error 

### ISSUE THREAD

**Issue by santhosh0209** [HafidzN/Inschatgram-Server#2]
**### These are the login errors:**
This is the console box message
> :5000/api/auth/login:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
> Object
> message: "secretOrPrivateKey must have a value"
> __proto__: Object

I also get the same **secretOrPrivateKey must have a value** above the login box

**### These are the signup errors:**

got errors in this codes and the error is

> 
> TypeError: Cannot read property 'find' of undefined
> (anonymous function)
> C:/Users/santhosh/Desktop/insta/src/components/screens/Signup.jsx:50
>   47 | 
>   48 | setError( currentState =>({
>   49 |    ...currentState,
> > 50 |    errorPassword : errors.find(err => err.param === 'password')?errors.msg:'',
>      | ^  51 |    errorEmail    : errors.find(err => err.param === 'email')   ?errors.msg:'',
>   52 |    errorFullname : errors.find(err => err.param === 'fullname')?errors.msg:'',
>   53 |    errorUsername : errors.find(err => err.param === 'username')?errors.msg:''
> 

kindly help me.

**Comment by HafidzN** [comment]
You are able to replace process.env.SECRET with whatever arbitrary alphanumeric string combination such as '!T5@s3cret', 'A5fhud363', or anything you want for the first issue. Its because i hide the jwt secret string in dotenv file.
But for the second issue you could wait a moment till i fix the trouble. Thanks for reporting the bug.

**Comment by santhosh0209** [comment]
Yes mam solved that problem everything okay but the values are not updating
when we edit profile that's the only problem now

Thank you for your patient response

**Comment by HafidzN** [comment]
Edit Profile only provides updates for photo and bio. You can develop it for the rest whole information by your own

**Comment by santhosh0209** [comment]
Any clues or hint for updating username????
And my final qn....how to combine the server and project together for
deployment

**Comment by HafidzN** [comment]
Try adapting the existing method you've seen inside the component for bio value. Then do not forget to also modify the related codes for updateProfile inside the userControllers file.

You can run both server and client into one single big file by using npm concurrently. But i think you'd better divide them into different file for handling performance and security issues in the future.

**Comment by santhosh0209** [comment]
Thanks for your reply
Whenever I am lagging your are the one who is helping me thanks
